### ISSUE TITLE
aiida-sssp and aiida-core have confliction on the requirement for click package.

### ISSUE THREAD

**Issue by hongyi-zhao** [aiidateam/aiida-sssp#3]
Hi,

See the following:

`aiida-core 1.1.1 has requirement click==7.0`

`aiida-sssp 0.1.0 has requirement click~=7.1`

So the two packages are incompatible.  But if I change the version config in setup.json of aiida-core for this package to the following:

`  click~=7.1`

This problem will disappear, but I still not so clear whether this this intentional revision will compromise the functions.

Regards

**Comment by sphuber** [comment]
Hi @hongyi-zhao , I am aware of this. This package is brand new and is still under development. For that reason it also doesn't have a release on PyPI yet. What I am building here will depend on `aiida-core==1.2.0` which should be released soon. I will make sure to remove the conflicts. Currently `aiida-core` had to pin `click` to version `7.0` see [this issue](https://github.com/aiidateam/aiida-core/issues/3838)

**Comment by hongyi-zhao** [comment]
@sphuber Strange, when I use the following steps to build conda-based AiiDA environment, the click version==7.1.1.  I let cona's SAT resolver to automatically find the dependencies.  See the following for detail:

```
$ pyenv shell anaconda3-2020.02
$ conda create -n aiida aiida-core
$ pyenv shell aiida
$ conda list | grep click
click                     7.1.1                      py_0    defaults
```

**Comment by sphuber** [comment]
This is because the change was added in [this PR](https://github.com/aiidateam/aiida-core/pull/3837) which has not been released yet. So the version you are installing `aiida-core==1.1.1` still comes with the newer version of click. The reason we had to pin is because our devops chain is broken, not `aiida-core` itself.

**Comment by hongyi-zhao** [comment]
Another strange problem, see my following description:

Based on the above constructed AiiDA environment, I run the this example given [here](https://aiida-tutorials.readthedocs.io/en/latest/_downloads/41fc098a6347cd8d1653a71b79cc51eb/launch_auto-wannier_workflow.py)

I've prepared all of the relative tools/plugins.  But when I run this example, I meet the following error:

```
$ python launch_auto-wannier_workflow.py GaAs.xsf 
launched WorkChain<235> for structure AsGa
Use `verdi process list` or `verdi process show 235` to check the progress
$ verdi process show 235
Property     Value
-----------  ------------------------------------------------------------------------------------------------
type         Wannier90BandsWorkChain
state        Excepted <TypeError: seekpath_structure_analysis() takes 1 positional arguments but 2 were given
             >
pk           235
```

OTOH, I can run this example within the Quantum Mobile successfully.

Any hints for this?

Regards

**Comment by sphuber** [comment]
This seems to be rather a problem with the `Wannier90BandsWorkChain`. I am not sure from which package it comes, maybe `aiida-wannier90-workflows`? Looking in their source code [this seems to be the offending line](https://github.com/aiidateam/aiida-wannier90-workflows/blob/cfc93b72f3ff1cd6f819dd7247eeae5fbe5820aa/aiida_wannier90_workflows/workflows/bands.py#L233).  It reads:
```
result = seekpath_structure_analysis(self.inputs.structure, seekpath_parameters)
```
but should read
```
result = seekpath_structure_analysis(self.inputs.structure, **kwargs)
```
I have opened an issue on [`aiida-wannier90-workflows`](https://github.com/aiidateam/aiida-wannier90-workflows/issues/3).

**Comment by hongyi-zhao** [comment]
This similar code also exists in aiida-vasp, see [here](https://github.com/aiida-vasp/aiida-vasp/blob/d089ed72ef3543d084d823a9345609a06fd271ba/aiida_vasp/workchains/bands.py#L259).

This is correct or not?

Regards

**Comment by sphuber** [comment]
That shouldn't have the same problem, because they define that function themselves in the same file. They don't depend on the function that ships with `aiida-quantumespresso`.

**Comment by hongyi-zhao** [comment]
> This seems to be rather a problem with the `Wannier90BandsWorkChain`. I am not sure from which package it comes, maybe `aiida-wannier90-workflows`? Looking in their source code [this seems to be the offending line](https://github.com/aiidateam/aiida-wannier90-workflows/blob/cfc93b72f3ff1cd6f819dd7247eeae5fbe5820aa/aiida_wannier90_workflows/workflows/bands.py#L233). It reads:
> 
> ```
> result = seekpath_structure_analysis(self.inputs.structure, seekpath_parameters)
> ```
> 
> but should read
> 
> ```
> result = seekpath_structure_analysis(self.inputs.structure, **kwargs)
> ```

I tried this revision, but meet the following error:
```

(aiida) werner@ubuntu-01:~/aiida$ python launch_auto-wannier_workflow.py GaAs.xsf 
launched WorkChain<265> for structure AsGa
Use `verdi process list` or `verdi process show 265` to check the progress
(aiida) werner@ubuntu-01:~/aiida$ verdi process show 265
Property     Value
-----------  -------------------------------------------------
type         Wannier90BandsWorkChain
state        Excepted <NameError: name 'kwargs' is not defined
             >
```



> 
> I have opened an issue on [`aiida-wannier90-workflows`](https://github.com/aiidateam/aiida-wannier90-workflows/issues/3).

**Comment by csadorf** [comment]
@sphuber This issue can be closed, right?

**Comment by sphuber** [comment]
I was waiting for `aiida-core==1.2.0` to be released (which should be today or tomorrow) and then I will update this to depend on that and fix the dependencies. Anyway, this package will rely on functionality that will ship with v1.2
